name: SYCL Eigenvalue Solver Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Intel oneAPI
      run: |
        wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/992857b9-624c-45de-9701-f6445d845359/l_BaseKit_p_2024.0.0.49563_offline.sh
        chmod +x l_BaseKit_p_2024.0.0.49563_offline.sh
        sudo ./l_BaseKit_p_2024.0.0.49563_offline.sh -a --silent --eula accept --components intel.oneapi.lin.dpcpp-cpp-compiler:intel.oneapi.lin.mkl.devel
    
    - name: Compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        icpx -fsycl -DMKL_ILP64 -m64 -I${MKLROOT}/include -L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl sycl_eigen_solver.cpp -o sycl_eigen_solver
    
    - name: Run benchmark
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./sycl_eigen_solver 8000 