name: SYCL Eigenvalue Solver Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Intel oneAPI
      uses: intel/setup-oneapi@v1
      with:
        components: 'intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmkl-full-dev
    
    - name: Compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        dpcpp -DMKL_ILP64 -m64 -I${MKLROOT}/include -L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl sycl_eigen_solver.cpp -o sycl_eigen_solver
    
    - name: Run benchmark
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./sycl_eigen_solver 8000 