name: SYCL Eigenvalue Solver Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-hpckit
    steps:
      - uses: actions/checkout@v4
      - name: oneAPI env
        run: source /opt/intel/oneapi/setvars.sh
      - name: Build
        run: |
          icpx -fsycl -O3 sycl_eigen_solver.cpp \
               $(pkg-config --cflags --libs mkl-sycl-ilp64) \
               -o sycl_eigen_solver
